// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4vZC93_JWKMcotZsMXyq_f5kNLtiqxFI',
    appId: '1:615927274378:web:94e5bc2cb0925a5c5c0673',
    messagingSenderId: '615927274378',
    projectId: 'lifesphere-essentials',
    authDomain: 'lifesphere-essentials.firebaseapp.com',
    storageBucket: 'lifesphere-essentials.firebasestorage.app',
    measurementId: 'G-7K34KTSH6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD58Si_xjtGUtJmuUAVEeJdsKY7HhGxYw',
    appId: '1:615927274378:android:0ba458e46a084d295c0673',
    messagingSenderId: '615927274378',
    projectId: 'lifesphere-essentials',
    storageBucket: 'lifesphere-essentials.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnJCQz002c3MQ-FjaTNHoKyJNRW58sd1o',
    appId: '1:615927274378:ios:0f8026b5684574f55c0673',
    messagingSenderId: '615927274378',
    projectId: 'lifesphere-essentials',
    storageBucket: 'lifesphere-essentials.firebasestorage.app',
    iosBundleId: 'com.example.lifesphereEssentials',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnJCQz002c3MQ-FjaTNHoKyJNRW58sd1o',
    appId: '1:615927274378:ios:0f8026b5684574f55c0673',
    messagingSenderId: '615927274378',
    projectId: 'lifesphere-essentials',
    storageBucket: 'lifesphere-essentials.firebasestorage.app',
    iosBundleId: 'com.example.lifesphereEssentials',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4vZC93_JWKMcotZsMXyq_f5kNLtiqxFI',
    appId: '1:615927274378:web:217cafe9bdb747ce5c0673',
    messagingSenderId: '615927274378',
    projectId: 'lifesphere-essentials',
    authDomain: 'lifesphere-essentials.firebaseapp.com',
    storageBucket: 'lifesphere-essentials.firebasestorage.app',
    measurementId: 'G-2YXY0413X2',
  );
}
